algoritmo "FarenheitCelsius"
// Função :Converter uma temperatura de farenheit para celsius
// Autor :Érick
// Data : 4/10/2021
// Seção de Declarações 
var
celsius, farenheit:real
inicio
// Seção de Comandos 

escreval("**********Conversor de Temperatura**********")
escreva("**********Qual é a temperatura em Farenheit: ")
leia(farenheit)
celsius <- (5/9)*(farenheit-32)

escreval("**********A temperatura equivalente em celsius é", celsius,"**********")
fimalgoritmo
