algoritmo "PerimetroAreaQuadrado"
// Função : Encontrar atraves dos lados de um quadrado seu perimetro e area
// Autor :Erick
// Data : 3/10/2021
// Seção de Declarações 
var

lado, perimetro,area:real

inicio
// Seção de Comandos 

escreva("Qual a medida do lado do quadrado: ")
leia(lado)

perimetro <- 4*lado
area <- lado^2

escreva("O quadrado de lado ",lado," possui perimetro de ",perimetro," e area de ",area)
fimalgoritmo
