algoritmo "ResistenciaEquivalente"
// Função : Calcular a ressistencia equivalente de um circuito de acordo
//          com a situacao problema.
// Autor :Erick
// Data : 8/10/2021
// Seção de Declarações 
var

inicio
// Seção de Comandos 

// Um circuito elétrico é composto de duas resistências R1 e R2 em paralelo, e
// ambas emsequência de uma resistência R3. Faça um algoritmo para calcular a
// resistência equivalente desse circuito.


fimalgoritmo
